### ISSUE TITLE
Request: change pydantic version to <= 3.0

### ISSUE THREAD

**Issue by FyZzyss** [flipt-io/flipt-python#20]
Please, change pydantic version to <= 3.0. Pydantic already has 2.5.2 tag. 

I start big migration from Pydantic 1.x to 2.5.2 and flipt only one is blocking this.

Thanks

**Comment by markphelps** [comment]
@FyZzyss , yes. we will be moving away from the autogenerated version of these server-side evaluation clients and instead move to managing them manually which allows us to change these dependencies ourselves. 

Then I can make this change. I am to start this migration this week and hopefully have new releases of our server-side clients out in the next week or two.

**Comment by FyZzyss** [comment]
@markphelps 
This is a bit selfish, but can we make a minor update for all pydantic 2.x? I will attach pr https://github.com/flipt-io/flipt-python/pull/22.
Started a major migration and got stuck with this in the middle of the process, I would be very happy to have the opportunity to continue.

**Comment by markphelps** [comment]
Yeah so the problem is that Fern will overwrite this change on the next generation. See #21 for an example.

Can you rebase this change onto #21 , then I can merge both PRs and create a release (0.2.17).

I will just have to make a note to manually update `poetry.lock` and `pyproject.toml` in each later Fern generated PR, until we can move off of Fern and handle this client entirely ourselves

**Comment by FyZzyss** [comment]
@markphelps It seems like I rebased

**Comment by markphelps** [comment]
Just released v0.2.17 with this fix. Thanks @FyZzyss ! lmk if it works for you

**Comment by FyZzyss** [comment]
@markphelps It works! Thanks a lot! You are the best ❤️
